name: ubuntu

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup prerequisites
        run: |
          sudo apt-get update
          sudo apt-get -y install p7zip-full

      - name: Build
        run: |
          make all

      - name: Run tests
        env:
          MN_PDF_FONT_PATH: ~/.fonts
        run: |
          make test
